### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by basickarl** [austinkelleher/lasso-use-strict#1]
Hi, I don't think I'm using this plugin correctly!
```
const lassoUseStrict = require('lasso-use-strict');
require('lasso').configure({
    plugins: [
        lassoUseStrict,
        'lasso-sass',
        'lasso-marko'
    ],
    require: {
        transforms: [{
            transform: 'lasso-babel-transform',
            config: {
                // directly specify babel options
                babelOptions: {
                    presets: ['@babel/preset-env']
                }
            }
        }]
    }
});
```
I get this:
```
TypeError: callback is not a function
    at Object.transform (/home/karl/dev/langurama/node_modules/lasso-use-strict/index.js:16:7)
    at applyTransform (/home/karl/dev/langurama/node_modules/lasso/src/transforms.js:62:30)
    at Stream.end (/home/karl/dev/langurama/node_modules/lasso/src/transforms.js:24:35)
    at _end (/home/karl/dev/langurama/node_modules/through/index.js:65:9)
    at Stream.stream.end (/home/karl/dev/langurama/node_modules/through/index.js:74:5)
    at PassThrough.onend (_stream_readable.js:651:10)
    at Object.onceWrapper (events.js:277:13)
    at PassThrough.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by austinkelleher** [comment]
@basickarl hey thanks for reaching out. My guess is that this is because you're using Lasso 3. Is that correct? Lasso 3 does not support callbacks in plugins. We should update this plugin to support both Lasso 2 and Lasso 3. I think it should be a fairly straightforward change. Here is the problem code:

https://github.com/austinkelleher/lasso-use-strict/blob/master/index.js#L16

I think the only change that needs to be made is something like:

```js
transform: function (code, lassoContext, callback) {
    ...

    if (callback) { 
      callback(null, code);
    }

   return code;
}
```

Would you be interested in trying this out and opening a PR?
